### ISSUE TITLE
Trombeta de Horwitz

### ISSUE THREAD

**Issue by juoceano** [juoceano/chemicaloceanography2#1]
@ocefpaf
- [ ]  Trombeta de Horwitz (CV= 2^(1-0.5 logC, onde C = concentração)

:boar::boar::boar::boar::boar::boar::boar::boar::boar::boar::boar:

**Comment by ocefpaf** [comment]
É pra fazer um gráfico da Trombeta?  Não entendi :confused:

**Comment by juoceano** [comment]
Isso, mas eu quero aprender como faz. Porque está difícil achar um figura com a trompeta que seja CC. Aí pensei que eu poderia fazer a minha.

**Comment by ocefpaf** [comment]
Reproduzi essa de um paper que achei online.  Começa modificando ela:

http://nbviewer.ipython.org/gist/ocefpaf/b93366c65271c99ac392

**Comment by juoceano** [comment]
Tem como você me mandar o cógido? Queria traduzir os textos.

**Comment by ocefpaf** [comment]
Feito em #2
